# SSI Ecosystem
# Copyright (c) 2026-present Izylife Solutions s.r.l.
# Author: Giuseppe Cassata
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

services:
  ssi-issuer-verifier:
    build:
      context: ./ssi-issuer-verifier
    restart: unless-stopped
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/ssi-issuer-verifier
      SPRING_DATA_MONGODB_DATABASE: ssi-issuer-verifier
      APP_ISSUER_ENDPOINT: https://izylife-issuer.eu.ngrok.io
      APP_VERIFIER_ENDPOINT: https://izylife-issuer.eu.ngrok.io
      SERVER_FORWARD_HEADERS_STRATEGY: framework
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"

  ssi-client:
    build:
      context: ./ssi-client-application
    restart: unless-stopped
    ports:
      - "9091:9091"
