server:
  port: 9090

app:
  issuer:
    organization-name: Izylife Public Authority
    endpoint: ${APP_ISSUER_ENDPOINT:https://mica-semicivilized-heavily.ngrok-free.dev}
    credential-issuer-id: ${APP_ISSUER_CREDENTIAL_ISSUER_ID:${APP_ISSUER_ENDPOINT:https://mica-semicivilized-heavily.ngrok-free.dev}}
    credential-offer-uri: ${APP_ISSUER_CREDENTIAL_OFFER_URI:}
    signing-key:
      kid: demo-issuer-key
      kty: EC
      crv: P-256
      x: yUkiMuYe-e1Kf-bJ0zPP3e7MUqhdN8-E-u9jjPywPjo
      y: WxCnkmraRMwnb2-GymcA-TP-CrEv3sLsLlS7iWhQC4c
      d: G-78W0e4pV0lTLuHNc8X96a_j3BIbjaa2avYeghwcAU
      alg: ES256
  verifier:
    endpoint: ${APP_VERIFIER_ENDPOINT:http://verifier.izylife.com:9090}
    challenge: demo-challenge
    qr-payload: "ssi://vp-request?audience=IzylifeVerifier&challenge=demo-challenge"
    client-id: ${APP_VERIFIER_ENDPOINT:http://verifier.izylife.com:9090}/oidc4vp/responses
    client-id-scheme: redirect_uri
    response-mode: direct_post
    request-audience: https://self-issued.me/v2
    presentation-definition-id: staff-credential
    signing-key:
      kid: demo-verifier-key
      kty: EC
      crv: P-256
      x: hVx-X9SsBBdC7TEzEo0mr5JvDifiW8ukP-dtmzYn1gs
      y: 0bYC51lu9R37eLSgtdK9gQLxjYMNgNcHapcq8xZ9YjI
      d: pSxjopWQyhwMpCpJ9OJ4uRi41-0usfuzEHhLul1PccE
      alg: ES256
  cors:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8080
      - https://staff-credentials.com
      - https://wallet.staff-credentials.com
      - https://*.staff-credentials.com
      - https://*.ngrok-free.app
    allow-credentials: false
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ssi-issuer-verifier}
      database: ${SPRING_DATA_MONGODB_DATABASE:ssi-issuer-verifier}
  mvc:
    static-path-pattern: /**
